//! Python Signal Relay Strategy
//!
//! Reads a JSON file exported by the Python research layer and re-emits
//! the signals as [`SignalEvent`]s into the Rust execution engine.
//!
//! ## Hot-path design
//! [`PythonSignalRelay::on_tick`] is called on every market tick (potentially
//! tens of thousands of times per second). To keep latency under 5µs:
//! - File I/O is **not** performed on every tick.
//! - Instead, the file is polled at a configurable interval (default 1 s).
//! - Signals are cached in-memory; `on_tick` only does a `HashMap` lookup.
//!
//! ## Stale-signal handling
//! If the cached signal for an instrument is older than `stale_threshold_secs`,
//! a flat signal (`side = None`, `strength = 0.0`) is emitted. This causes the
//! execution engine to flatten any open position safely.

use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;
use std::time::{Duration, Instant};

use serde::Deserialize;

use quantfund_core::types::Side;
use quantfund_core::{InstrumentId, SignalEvent, StrategyId, Timestamp};

use crate::traits::{MarketSnapshot, Strategy};

// ---------------------------------------------------------------------------
// JSON wire format (matches Python `RustSignalEvent.to_rust_json()`)
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct RawTimestamp {
    nanos_since_epoch: i64,
}

#[derive(Debug, Deserialize)]
struct RawSignal {
    timestamp: RawTimestamp,
    strategy_id: String,
    instrument_id: String,
    side: Option<String>,
    strength: f64,
    metadata: serde_json::Value,
}

impl RawSignal {
    fn parse_side(&self) -> Option<Side> {
        match self.side.as_deref() {
            Some("Buy") => Some(Side::Buy),
            Some("Sell") => Some(Side::Sell),
            _ => None,
        }
    }
}

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

/// Configuration for [`PythonSignalRelay`].
#[derive(Clone, Debug)]
pub struct PythonSignalRelayConfig {
    /// Path to the JSON file written by the Python signal loop.
    pub signals_path: PathBuf,
    /// How often to re-read the file (milliseconds). Default: 1000.
    pub poll_interval_ms: u64,
    /// Signals older than this many seconds are treated as stale. Default: 60.
    pub stale_threshold_secs: i64,
    /// Instruments managed by this relay.
    pub instruments: Vec<InstrumentId>,
    /// Strategy identifier embedded in emitted [`SignalEvent`]s.
    pub strategy_id: String,
}

impl Default for PythonSignalRelayConfig {
    fn default() -> Self {
        Self {
            signals_path: PathBuf::from("export/signals_latest.json"),
            poll_interval_ms: 1_000,
            stale_threshold_secs: 60,
            instruments: vec![InstrumentId::new("EURUSD")],
            strategy_id: "python-relay".to_string(),
        }
    }
}

// ---------------------------------------------------------------------------
// Cached signal
// ---------------------------------------------------------------------------

#[derive(Clone, Debug)]
struct CachedSignal {
    timestamp_ns: i64,
    side: Option<Side>,
    strength: f64,
    metadata: serde_json::Value,
}

impl CachedSignal {
    /// Flat / neutral signal (flatten position).
    fn flat() -> Self {
        Self {
            timestamp_ns: 0,
            side: None,
            strength: 0.0,
            metadata: serde_json::json!({}),
        }
    }
}

// ---------------------------------------------------------------------------
// PythonSignalRelay
// ---------------------------------------------------------------------------

/// Rust strategy that forwards signals generated by the Python research layer.
pub struct PythonSignalRelay {
    id: StrategyId,
    config: PythonSignalRelayConfig,
    /// Per-instrument cached signals.
    cached: HashMap<String, CachedSignal>,
    /// Wall-clock time of the last successful file read.
    last_poll: Option<Instant>,
    poll_interval: Duration,
}

impl PythonSignalRelay {
    /// Create a new relay with the given configuration.
    pub fn new(config: PythonSignalRelayConfig) -> Self {
        let poll_interval = Duration::from_millis(config.poll_interval_ms);
        let id = StrategyId::new(config.strategy_id.clone());
        Self {
            id,
            config,
            cached: HashMap::new(),
            last_poll: None,
            poll_interval,
        }
    }

    // ------------------------------------------------------------------
    // File polling
    // ------------------------------------------------------------------

    /// Poll the signals file if the poll interval has elapsed.
    ///
    /// `now_ns` is the current engine timestamp (nanoseconds since epoch),
    /// used to detect stale signals.
    fn maybe_refresh(&mut self, now_ns: i64) {
        let should_poll = self
            .last_poll
            .map(|t| t.elapsed() >= self.poll_interval)
            .unwrap_or(true); // always poll on first call

        if should_poll {
            self.refresh_from_disk(now_ns);
            self.last_poll = Some(Instant::now());
        }
    }

    /// Read the JSON file and update the in-memory cache.
    fn refresh_from_disk(&mut self, now_ns: i64) {
        let content = match fs::read_to_string(&self.config.signals_path) {
            Ok(c) => c,
            Err(e) => {
                tracing::warn!(
                    path = %self.config.signals_path.display(),
                    error = %e,
                    "PythonSignalRelay: could not read signals file"
                );
                return;
            }
        };

        let raw_signals: Vec<RawSignal> = match serde_json::from_str(&content) {
            Ok(v) => v,
            Err(e) => {
                tracing::warn!(error = %e, "PythonSignalRelay: JSON parse error");
                return;
            }
        };

        let stale_cutoff_ns = now_ns - self.config.stale_threshold_secs * 1_000_000_000;

        // Build a set of managed instrument IDs for fast lookup
        let managed: std::collections::HashSet<&str> = self
            .config
            .instruments
            .iter()
            .map(|id| id.as_str())
            .collect();

        for raw in raw_signals {
            let ts_ns = raw.timestamp.nanos_since_epoch;

            if raw.strategy_id != self.config.strategy_id {
                continue;
            }

            // Skip instruments we don't manage
            if !managed.contains(raw.instrument_id.as_str()) {
                continue;
            }

            // Skip stale signals
            if ts_ns < stale_cutoff_ns {
                tracing::debug!(
                    instrument = %raw.instrument_id,
                    "PythonSignalRelay: dropping stale signal"
                );
                continue;
            }

            let strength = raw.strength.clamp(-1.0, 1.0);
            let cached = CachedSignal {
                timestamp_ns: ts_ns,
                side: raw.parse_side(),
                strength,
                metadata: raw.metadata,
            };
            self.cached.insert(raw.instrument_id, cached);
        }
    }

    // ------------------------------------------------------------------
    // Signal emission
    // ------------------------------------------------------------------

    /// Emit a [`SignalEvent`] for the given instrument.
    ///
    /// Returns a flat signal if no cached entry exists.
    fn emit_signal(
        &self,
        instrument_id: &InstrumentId,
        tick_ts: Timestamp,
        now_ns: i64,
    ) -> SignalEvent {
        let stale_cutoff_ns = now_ns - self.config.stale_threshold_secs * 1_000_000_000;
        let cached = self
            .cached
            .get(instrument_id.as_str())
            .cloned()
            .filter(|signal| signal.timestamp_ns >= stale_cutoff_ns)
            .unwrap_or_else(CachedSignal::flat);

        SignalEvent {
            timestamp: tick_ts,
            strategy_id: self.id.clone(),
            instrument_id: instrument_id.clone(),
            side: cached.side,
            strength: cached.strength,
            metadata: cached.metadata,
        }
    }
}

// ---------------------------------------------------------------------------
// Strategy impl
// ---------------------------------------------------------------------------

impl Strategy for PythonSignalRelay {
    fn id(&self) -> &StrategyId {
        &self.id
    }

    fn name(&self) -> &str {
        "Python Signal Relay"
    }

    fn instruments(&self) -> &[InstrumentId] {
        &self.config.instruments
    }

    fn on_tick(&mut self, snapshot: &MarketSnapshot) -> Option<SignalEvent> {
        let now_ns = snapshot.tick.timestamp.as_nanos();
        self.maybe_refresh(now_ns);

        let signal = self.emit_signal(snapshot.instrument_id, snapshot.tick.timestamp, now_ns);

        // Return None only when fully flat (side=None AND strength≈0)
        if signal.side.is_none() && signal.strength.abs() < 1e-9 {
            return None;
        }

        Some(signal)
    }

    fn reset(&mut self) {
        self.cached.clear();
        self.last_poll = None;
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use quantfund_core::{Price, TickEvent, Volume};
    use rust_decimal_macros::dec;
    use std::io::Write;
    use tempfile::NamedTempFile;

    fn make_tick(instrument: &str, ts_nanos: i64) -> TickEvent {
        TickEvent {
            timestamp: Timestamp::from_nanos(ts_nanos),
            instrument_id: InstrumentId::new(instrument),
            bid: Price::new(dec!(1.1000)),
            ask: Price::new(dec!(1.1002)),
            bid_volume: Volume::new(dec!(100)),
            ask_volume: Volume::new(dec!(100)),
            spread: dec!(0.0002),
        }
    }

    fn make_snapshot<'a>(tick: &'a TickEvent, id: &'a InstrumentId) -> MarketSnapshot<'a> {
        MarketSnapshot {
            tick,
            instrument_id: id,
        }
    }

    fn signal_json(ts_nanos: i64, side: &str, strength: f64) -> String {
        format!(
            r#"[{{"timestamp":{{"nanos_since_epoch":{ts_nanos}}},"strategy_id":"py","instrument_id":"EURUSD","side":{side},"strength":{strength},"metadata":{{}}}}]"#
        )
    }

    #[test]
    fn no_signal_when_file_missing() {
        let config = PythonSignalRelayConfig {
            signals_path: PathBuf::from("/nonexistent/path/signals.json"),
            poll_interval_ms: 0,
            instruments: vec![InstrumentId::new("EURUSD")],
            ..Default::default()
        };
        let mut relay = PythonSignalRelay::new(config);
        let id = InstrumentId::new("EURUSD");
        let tick = make_tick("EURUSD", 1_000_000_000);
        let snapshot = make_snapshot(&tick, &id);

        // Missing file → no signal (flat returns None)
        assert!(relay.on_tick(&snapshot).is_none());
    }

    #[test]
    fn emits_signal_from_json_file() {
        let ts_nanos: i64 = 1_700_000_000_000_000_000; // well within threshold
        let mut tmp = NamedTempFile::new().unwrap();
        let json = signal_json(ts_nanos, r#""Buy""#, 0.75);
        tmp.write_all(json.as_bytes()).unwrap();
        tmp.flush().unwrap();

        let config = PythonSignalRelayConfig {
            signals_path: tmp.path().to_path_buf(),
            poll_interval_ms: 0,
            stale_threshold_secs: 3600,
            instruments: vec![InstrumentId::new("EURUSD")],
            strategy_id: "py".to_string(),
            ..Default::default()
        };
        let mut relay = PythonSignalRelay::new(config);
        let id = InstrumentId::new("EURUSD");
        let tick = make_tick("EURUSD", ts_nanos + 1_000_000_000); // 1s after signal
        let snapshot = make_snapshot(&tick, &id);

        let signal = relay.on_tick(&snapshot).expect("expected a signal");
        assert_eq!(signal.side, Some(Side::Buy));
        assert!((signal.strength - 0.75).abs() < 1e-9);
    }

    #[test]
    fn stale_signal_returns_none() {
        let old_ts_nanos: i64 = 1_000_000_000; // epoch + 1s
        let mut tmp = NamedTempFile::new().unwrap();
        let json = signal_json(old_ts_nanos, r#""Buy""#, 0.5);
        tmp.write_all(json.as_bytes()).unwrap();
        tmp.flush().unwrap();

        let now_ns: i64 = old_ts_nanos + 120 * 1_000_000_000; // 2 minutes later
        let config = PythonSignalRelayConfig {
            signals_path: tmp.path().to_path_buf(),
            poll_interval_ms: 0,
            stale_threshold_secs: 60,
            instruments: vec![InstrumentId::new("EURUSD")],
            ..Default::default()
        };
        let mut relay = PythonSignalRelay::new(config);
        let id = InstrumentId::new("EURUSD");
        let tick = make_tick("EURUSD", now_ns);
        let snapshot = make_snapshot(&tick, &id);

        // Stale → flat → on_tick returns None
        assert!(relay.on_tick(&snapshot).is_none());
    }

    #[test]
    fn clamps_strength_to_unit_interval() {
        let ts_nanos: i64 = 1_700_000_000_000_000_000;
        let mut tmp = NamedTempFile::new().unwrap();
        // strength = 5.0 → should be clamped to 1.0
        let json = signal_json(ts_nanos, r#""Buy""#, 5.0);
        tmp.write_all(json.as_bytes()).unwrap();
        tmp.flush().unwrap();

        let config = PythonSignalRelayConfig {
            signals_path: tmp.path().to_path_buf(),
            poll_interval_ms: 0,
            stale_threshold_secs: 3600,
            instruments: vec![InstrumentId::new("EURUSD")],
            strategy_id: "py".to_string(),
            ..Default::default()
        };
        let mut relay = PythonSignalRelay::new(config);
        let id = InstrumentId::new("EURUSD");
        let tick = make_tick("EURUSD", ts_nanos + 1_000_000_000);
        let snapshot = make_snapshot(&tick, &id);

        let signal = relay.on_tick(&snapshot).expect("expected a signal");
        assert!(
            (signal.strength - 1.0).abs() < 1e-9,
            "strength={}",
            signal.strength
        );
    }

    #[test]
    fn reset_clears_cached_signals() {
        let ts_nanos: i64 = 1_700_000_000_000_000_000;
        let mut tmp = NamedTempFile::new().unwrap();
        let json = signal_json(ts_nanos, r#""Sell""#, -0.6);
        tmp.write_all(json.as_bytes()).unwrap();
        tmp.flush().unwrap();

        let config = PythonSignalRelayConfig {
            signals_path: tmp.path().to_path_buf(),
            poll_interval_ms: 0,
            stale_threshold_secs: 3600,
            instruments: vec![InstrumentId::new("EURUSD")],
            strategy_id: "py".to_string(),
            ..Default::default()
        };
        let mut relay = PythonSignalRelay::new(config);
        let id = InstrumentId::new("EURUSD");
        let tick = make_tick("EURUSD", ts_nanos + 1_000_000_000);
        let snapshot = make_snapshot(&tick, &id);

        // First tick: populates cache
        relay.on_tick(&snapshot).expect("expected a signal");
        assert!(!relay.cached.is_empty());

        // Reset: clears cache and last_poll
        relay.reset();
        assert!(relay.cached.is_empty());
        assert!(relay.last_poll.is_none());
    }
}
